### ISSUE TITLE
Tagging requirements apparently wrong

### ISSUE THREAD

**Issue by Savisimo** [yarl/osmtools-indoor#5]
I've tagged the Liceo Scientifico in Vercelli according to what the wiki says. You can find it here: http://osmtools.org/indoor/#lat=45.32404&lon=8.43049&z=18

The first issue I encountered was that I had to add a closed way as "outer" in the building relation - the wiki didn't mention it. Then, after I got the outline to render and I've been able to "enter" the building, yesterday the whole building "disappeared" (it was no more drawn). I read the javascript and found out I had to tag the outer with level=0 and building=yes - again, not mentioned in the wiki. 

Now, however, even if the popup appears and I click "Enter", the loading icon appears and the application is stuck there. I can move the map around, but no building navigation option is available. 

I think I tagged the building according to the wiki specifications. Could you please check what's wrong?

**Comment by yarl** [comment]
There was small error in your tagging, I fixed it in [changeset 14547506](http://www.openstreetmap.org/browse/changeset/14547506). Outline of level should have role 'shell' instead of 'outer'.

If you want to be sure, that building will be rendered correctly, there is a [short instruction](https://github.com/yarl/osmtools-indoor#readme) at project main page.

**Comment by Savisimo** [comment]
Thanks, I didn't notice the instructions.
